"""fix project model types

Revision ID: 5e6edfa4f6b8
Revises: 6d9b5cfdd6dd
Create Date: 2026-09-10 13:42:43.020774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6edfa4f6b8'
down_revision: Union[str, Sequence[str], None] = '6d9b5cfdd6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
